/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TorqButton {
    /**
    * The text to show inside the button
    */
    'buttontext': string;
    /**
    * Four button choices are: primary, callToAction, outline, and text
    */
    'buttontype': string;
  }
  interface TorqButtonAttributes extends StencilHTMLAttributes {
    /**
    * The text to show inside the button
    */
    'buttontext'?: string;
    /**
    * Four button choices are: primary, callToAction, outline, and text
    */
    'buttontype'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TorqButton': Components.TorqButton;
  }

  interface StencilIntrinsicElements {
    'torq-button': Components.TorqButtonAttributes;
  }


  interface HTMLTorqButtonElement extends Components.TorqButton, HTMLStencilElement {}
  var HTMLTorqButtonElement: {
    prototype: HTMLTorqButtonElement;
    new (): HTMLTorqButtonElement;
  };

  interface HTMLElementTagNameMap {
    'torq-button': HTMLTorqButtonElement
  }

  interface ElementTagNameMap {
    'torq-button': HTMLTorqButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
